name: build

on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 1 * * *'

  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup pipenv virtual environment
        run: |
          pip install pipenv
          pipenv sync

      - name: Clone pvme-guides repository
        run: git clone --depth 1 https://github.com/pvme/pvme-guides.git

      - name: Generate sources
        run: pipenv run python formatter_cli.py --generate_mkdocs pvme-guides docs mkdocs.yml

      - name: Update website
        run: pipenv run mkdocs gh-deploy --force